rust: allow `invalid_runtime_symbol_definitions` lint for Rust >= 1.98
Starting with Rust 1.98.0 (expected 2026-08-20), Rust is introducing
a new deny-by-default lint which checks the signature of items whose
symbol name is a runtime symbol expected by `core`:

    error: invalid definition of the runtime `strlen` symbol used by the standard library
         --> rust/uapi/uapi_generated.rs:13998:5
          |
    13998 |     pub fn strlen(s: *const ffi::c_char) -> usize;
          |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          |
          = note: expected `unsafe extern "C" fn(*const i8) -> usize`
                  found    `unsafe extern "C" fn(*const u8) -> usize`
          = help: either fix the signature or remove any attributes like `#[unsafe(no_mangle)]`, `#[unsafe(export_name = "strlen")]`, or `#[link_name = "strlen"]`
          = note: `#[deny(invalid_runtime_symbol_definitions)]` on by default

    error: invalid definition of the runtime `strlen` symbol used by the standard library
         --> rust/bindings/bindings_generated.rs:19877:5
          |
    19877 |     pub fn strlen(s: *const ffi::c_char) -> usize;
          |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          |
          = note: expected `unsafe extern "C" fn(*const i8) -> usize`
                  found    `unsafe extern "C" fn(*const u8) -> usize`
          = help: either fix the signature or remove any attributes like `#[unsafe(no_mangle)]`, `#[unsafe(export_name = "strlen")]`, or `#[link_name = "strlen"]`
          = note: `#[deny(invalid_runtime_symbol_definitions)]` on by default

Thus `allow` the lint in `bindings` and `uapi`.

Link: https://github.com/rust-lang/rust/pull/155521 [1]
Signed-off-by: Miguel Ojeda <ojeda@kernel.org>